name: "bueno-ha"
description: "Connect Home Assistant to the Bueno platform (https://buenoanalytics.com/)"
version: "1.0.0"
slug: "bueno-ha"
init: false
homeassistant_api: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

options:
  entities: null
  bueno_integration_id: null
  bueno_api_url: null
  bueno_credentials:
    email: null
    password: null

schema:
  entities:
    - ha_sensor_id: str
      bueno_data_stream_id: str
  bueno_integration_id: str
  bueno_api_url: str
  bueno_credentials:
    email: email
    password: str
