name: "bueno-ha"
description: "Connect Home Assistant to the Bueno platform (https://buenoanalytics.com/)"
version: "1.0.0"
slug: "bueno-ha"
init: false
homeassistant_api: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
